### ISSUE TITLE
Absolute crap

### ISSUE THREAD

**Issue by darebgd** [longgui0318/comfyui-llm-assistant#4]
So, who is your target audience? Is it AI developers?
Because you published this shit on ComfyUI and me, as a common user who does not have too deep knowledge about how each model works, can't use your crappy node.

Why does it exist, which exactly problem does it solve, except the problem with your ego?
I think ComfyUI should filter nodes with no documentation AT ALL.

ADD frikkin documentation and explain how to frikkin use it. Where do I find the API key and how the hell I am supposed to guess that your .yaml file is something I need to rename so it works?

Frikkin OUT OF THE BOX is how big tech works, you moron.

_"I appreciate your hard work"_ more like I appreciate your flexing about your crappy LLM skills, specifically. Geeky nerd, compensating...

**Comment by longgui0318** [comment]
Writing a bunch of words just to vent emotions. You can make demands without doing anything else.
